---
title: "StudyCFA"
author: "Aman Jindal"
date: "23 February 2021"
output: 
  word_document: 
    keep_md: yes
---

# Fixed Income:

## 1. Fixed Income investments provides:
- diversification,
- regular cash flows and 
- inflation protection.

## 2. Types of Fixed Income Mandates:

### a. Liability Based Mandates:

i. **Cash-flow Matching:** 
    In this form of hedging the liability cash flows are exatly matched with the asset cash flows.<br>
ii. **Duration Matching:** 
    The duration of liabilities and assets are matched.<br>
iii. **Contingent Immunization:**
    As long as the Present Value of Assets (PVA) is more than the the Present Value of Liabilites (PVL), the portfolio could         be actively managed. However, if PVA becomes smaller than the PVL, then the portfolio must be immediately immunized.<br>
iv. **Horizon Matching:**
    This is an intermediate strategy between cash-flow matching and Duration matching. The short term liabilites are                 cash-flow matched, while the long term liabilities are duration matched.<br>

### b. Total Return Mandates:

i. **Pure Indexing**
ii. **Enhanced Indexing**
iii. **Active Management**
        

            
    
    
    
    
    
    